services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    expose:
      - 8080
    networks:
      - perplexica-network

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=https://us84occ.mcx.design
    depends_on:
      - searxng
    expose:
      - 3001
    networks:
      - perplexica-network

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://g8008gk.mcx.design/api
        - NEXT_PUBLIC_WS_URL=https://g8008gk.mcx.design
    depends_on:
      - perplexica-backend
    expose:
      - 3000
    networks:
      - perplexica-network

networks:
  perplexica-network:
